In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3],
              [4, 5, 6.5]])

a3 = np.array ([[[1, 2, 3],
                 [4, 5, 6]],
                 [[7, 8, 9],
                 [10, 11, 12]],
                  [[13, 14, 15],
                  [16, 17, 18]]])

In [5]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [6]:
a1.shape

(3,)

In [7]:
a2.shape

(2, 3)

In [8]:
a3.shape

(3, 2, 3)

In [9]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [10]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [11]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [12]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [13]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [14]:
# Create a DataFrame from a NumPy array
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating array

In [15]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [16]:
sample_array.dtype

dtype('int64')

In [17]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
ones.dtype

dtype('float64')

In [19]:
type(ones)

numpy.ndarray

In [20]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [22]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[7, 4, 1, 3, 3],
       [4, 8, 8, 0, 4],
       [9, 3, 8, 6, 9]], dtype=int32)

In [23]:
random_array.size

15

In [24]:
random_array.shape

(3, 5)

In [25]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.4452816 , 0.56436366, 0.06546407],
       [0.86501556, 0.43013321, 0.35995758],
       [0.84031651, 0.2102661 , 0.23931911],
       [0.31789268, 0.44892459, 0.92133739],
       [0.00564256, 0.41555465, 0.67060453]])

In [26]:
random_array_2.shape

(5, 3)

In [27]:
random_array_3 = np.random.rand(4, 3)
random_array_3

array([[0.58876835, 0.78754932, 0.83443407],
       [0.45121717, 0.95429893, 0.79230479],
       [0.07951748, 0.65545645, 0.16677894],
       [0.58907699, 0.90656848, 0.59809181]])

In [28]:
# Pseudo-random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

In [29]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [30]:
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

## 3. Viewing array and matrices

In [31]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [32]:
a1

array([1, 2, 3])

In [33]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [34]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [35]:
a1[0]

np.int64(1)

In [36]:
a2.shape

(2, 3)

In [37]:
a2[0]

array([1. , 2. , 3.3])

In [38]:
a3.shape

(3, 2, 3)

In [39]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [41]:
a2[1]

array([4. , 5. , 6.5])

In [42]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [43]:
a3[:3, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]],

       [[13, 14],
        [16, 17]]])

In [44]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[6, 7, 7, 9, 3],
         [0, 7, 7, 7, 0],
         [5, 4, 3, 1, 3],
         [1, 3, 4, 3, 1]],

        [[9, 5, 9, 1, 2],
         [3, 2, 2, 5, 7],
         [3, 0, 9, 9, 3],
         [4, 5, 3, 0, 4]],

        [[8, 6, 7, 2, 7],
         [3, 8, 6, 6, 5],
         [6, 5, 7, 1, 5],
         [4, 4, 9, 9, 0]]],


       [[[6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5],
         [1, 6, 9, 8, 6],
         [5, 9, 7, 5, 4]],

        [[9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7],
         [9, 4, 7, 5, 9],
         [6, 2, 0, 5, 3]],

        [[0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9]]]], dtype=int32)

In [45]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [46]:
# Get the first 4 numbers of the inner most arrays
a4[:, :, :, :1]

array([[[[6],
         [0],
         [5],
         [1]],

        [[9],
         [3],
         [3],
         [4]],

        [[8],
         [3],
         [6],
         [4]]],


       [[[6],
         [4],
         [1],
         [5]],

        [[9],
         [5],
         [9],
         [6]],

        [[0],
         [4],
         [7],
         [5]]]], dtype=int32)

## 4. Manipulating & comparing arrays

### Arithmetic

In [47]:
a1

array([1, 2, 3])

In [48]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [49]:
a1 + ones

array([2., 3., 4.])

In [50]:
a1 - ones

array([0., 1., 2.])

In [51]:
a1 * ones

array([1., 2., 3.])

In [52]:
a1

array([1, 2, 3])

In [53]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [54]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [55]:
a3.shape, a2.shape

((3, 2, 3), (2, 3))

In [56]:
a3_random = np.random.randint(10, size=(2,3,3))
a3_random

array([[[1, 1, 5],
        [3, 2, 0],
        [4, 8, 7]],

       [[1, 4, 9],
        [3, 6, 7],
        [1, 0, 2]]], dtype=int32)

In [57]:
# How can you reshape a2 to be compatibles with a3?
# Seaech: "How to reshape numpy array"
a2 * a3_random

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [ ]:
a1 / ones

In [ ]:
a2 / a1

In [ ]:
# Floor division removes the decimails (rounds down)
a2 // a1

In [ ]:
a2 ** 2

In [ ]:
np.square(a2)

In [ ]:
a1 + ones

In [ ]:
np.add(a1, ones)

In [ ]:
a1 % 2

In [ ]:
a1 / 2

In [ ]:
a2 % 2

In [ ]:
np.exp(a1)

In [ ]:
np.log(a1)

### Aggregation

Aggregation = performing th same operation on a number og thing

In [ ]:
listy_list = [1, 2,3 ]
type(listy_list)

In [ ]:
sum(listy_list)

In [ ]:
sum(a1)

In [ ]:
np.sum(a1)

In [ ]:
# Creative a massive NumPy array
massive_array = np.random.random(100000)
massive_array.size

In [ ]:
massive_array[:10]

In [ ]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # NumPy's np.sum()

In [ ]:
17900 /34

In [ ]:
a2

In [ ]:
np.mean(a2)

In [ ]:
np.max(a2)

In [ ]:
np.min(a2)

In [ ]:
np.std(a2)

In [ ]:
# Variance = measure of the averange degree to wich each number is different number to the mean
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers
np.var(a2)

In [ ]:
# Standard deviation = squareroot pf variance
np.sqrt(np.var(a2))

In [ ]:
# Demo of srd and var
high_var_array = np.array([1, 100, 200, 300, 4000, 5000])
low_var_array = np.array([2, 4, 5, 8, 10])

In [ ]:
np.var(high_var_array), np.var(low_var_array)

In [ ]:
np.std(high_var_array), np.std(low_var_array)

In [ ]:
np.mean(high_var_array), np.mean(low_var_array)

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.hist(high_var_array)
plt.show()

In [ ]:
plt.hist(low_var_array)
plt.show()

## Reshaping & transposing

In [ ]:
a2

In [ ]:
a2.shape

In [ ]:
a3_random

In [ ]:
a3_random.shape

In [ ]:
a2*a3_random

In [ ]:
a2.shape

In [ ]:
a2_reshape = a2.reshape(2, 3, 1)
a2_reshape

In [ ]:
a2_reshape * a3_random

In [ ]:
# Transpose = switches the axis's
a2.T

In [ ]:
a3_random.T

In [ ]:
a3_random.T.shape

## Dot product

In [ ]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))

mat1

In [ ]:
mat2

In [ ]:
mat1.shape, mat2.shape

In [ ]:
# Element-wise multiplication (Hadamard product)
mat1 * mat2

In [ ]:
# Dot product
np.dot(mat1, mat2)

In [ ]:
# Transpose mat1
mat1.T

In [ ]:
mat1.shape, mat2.T.shape

In [ ]:
mat3 = np.dot(mat1, mat2.T)
mat3

In [ ]:
mat3.shape

## Dot product example (nut butter sales)

In [ ]:
np.random.seed(0)
# Number of jars sold
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

In [ ]:
# Create weeklu_sales DataFrame
weekly_sales = pd.DataFrame(sales_amounts,
                            index=["Mon", "Tues", "Wed", "Thurs", "Fri"],
                            columns=["Almond butter", "Peanut butter", "Cashew butter"])

weekly_sales

In [ ]:
# Create prices array
prices = np.array([10, 8, 12])
prices

In [ ]:
# Create butter_prices DataFrame
butter_prices = pd.DataFrame(prices.reshape(1, 3),
                             index=["Price"],
                             columns=["Almond butter", "Peanut butter", "Cashew butter"])
butter_prices

In [ ]:
prices.shape

In [ ]:
sales_amounts.shape

In [ ]:
total_sales = prices.dot(sales_amount)

In [ ]:
# Shapes aren't alingned, let's transpose
total_sales = prices.dot(sales_amounts.T)
total_sales

In [ ]:
# Create daily_sales
butter_prices.shape, weekly_sales.shape

In [ ]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

In [ ]:
weekly_sales

In [ ]:
# Doesn't work, not the right shape
weekly_sales["Total (%)"] = daily_sales
weekly_sales

In [ ]:
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales.drop(["Teste"], axis=1, inplace=True)

In [ ]:
weekly_sales

## Comparison Operators

In [61]:
a1

array([1, 2, 3])

In [62]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [63]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [64]:
bool_array = a1 >= a2
bool_array

array([[ True,  True, False],
       [False, False, False]])

In [65]:
type(bool_array), bool_array.dtype

(numpy.ndarray, dtype('bool'))

In [68]:
a1 > 5

array([False, False, False])

In [69]:
a1 < 5

array([ True,  True,  True])

In [67]:
a1 == a2

array([[ True,  True, False],
       [False, False, False]])

## 5. Sorting arrays

In [78]:
random_array = np.random.randint(10, size=(3, 5))
random_array

array([[6, 2, 6, 8, 7],
       [0, 5, 8, 9, 7],
       [7, 6, 2, 5, 6]], dtype=int32)

In [79]:
np.sort(random_array)

array([[2, 6, 6, 7, 8],
       [0, 5, 7, 8, 9],
       [2, 5, 6, 6, 7]], dtype=int32)

In [82]:
random_array

array([[6, 2, 6, 8, 7],
       [0, 5, 8, 9, 7],
       [7, 6, 2, 5, 6]], dtype=int32)

In [81]:
np.argsort(random_array)

array([[1, 0, 2, 4, 3],
       [0, 1, 4, 2, 3],
       [2, 3, 1, 4, 0]])

In [83]:
a1

array([1, 2, 3])

In [84]:
np.argsort(a1)

array([0, 1, 2])

In [85]:
np.argmin(a1)

np.int64(0)

In [86]:
np.argmax(a1)

np.int64(2)

In [87]:
random_array

array([[6, 2, 6, 8, 7],
       [0, 5, 8, 9, 7],
       [7, 6, 2, 5, 6]], dtype=int32)

In [89]:
np.argmax(random_array, axis=0)

array([2, 2, 1, 1, 0])

In [90]:
np.argmax(random_array, axis=1)

array([3, 3, 0])

## 6. Pratical Example - NumPy in Action!!!

<img src="images/panda.png"/>

In [103]:
# Turn an image into a NumPy array
from matplotlib.image import imread

panda = imread("images/panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [105]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

In [106]:
panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.

<img src="images/car-photo.png"/>

In [107]:
car = imread("images/car-photo.png")
print(type(car))

<class 'numpy.ndarray'>


In [108]:
car[:1]

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]]],
      shape=(1, 575, 4), dtype=float32)

<img src="images/dog-photo.png"/>

In [110]:
dog = imread("images/dog-photo.png")
print(type(dog))

<class 'numpy.ndarray'>


In [112]:
dog

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]],

       [[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
        [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49411765, 0.68235296, 0.84313726, 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ]],

       [[0.6901961 , 0.8       , 0.88235295, 1.        ],
        [0.69803923, 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49803922, 0.686274