In [1]:
import numpy as np

In [6]:
a1D = np.array([1, 2, 3])
a1D

array([1, 2, 3])

In [7]:
a2D = np.array([[1, 2], [3, 4]])
a2D

array([[1, 2],
       [3, 4]])

In [8]:
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
a3D

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [10]:
a1D.shape, a1D.ndim, a1D.dtype, a1D.size, type(a1D)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [11]:
# Atributos de um array bidimensional
a2D.shape, a2D.ndim, a2D.dtype, a2D.size, type(a2D)

((2, 2), 2, dtype('int64'), 4, numpy.ndarray)

In [12]:
# Atributos de um array tridimensional
a3D.shape, a3D.ndim, a3D.dtype, a3D.size, type(a3D)

((2, 2, 2), 3, dtype('int64'), 8, numpy.ndarray)

In [14]:
# Importe o pandas e crie um DataFrame a partir de um dos arrays que você criou.
import pandas as pd
df = pd.DataFrame(a2D)
df

0  1
0  1  2
1  3  4

In [16]:
matriz_one = np.ones(shape=(10, 2))
matriz_one

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [17]:
matriz_zeros = np.zeros(shape=(7, 2, 3))
matriz_zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [18]:
range_array = np.arange(1, 100, 3)
range_array

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [19]:
random_array = np.random.randint(10, size=(7, 2))
random_array

array([[1, 6],
       [0, 5],
       [5, 6],
       [6, 3],
       [4, 4],
       [9, 8],
       [8, 7]], dtype=int32)

In [20]:
np.random.random((3, 5))

array([[0.06185625, 0.5068979 , 0.39972778, 0.29643807, 0.91453607],
       [0.25553815, 0.7893647 , 0.07666843, 0.58063087, 0.84163796],
       [0.54895041, 0.72535989, 0.21290229, 0.34380273, 0.71647769]])

In [24]:
np.random.seed(42)
np.random.randint(10, size=(4, 6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]], dtype=int32)

In [26]:
random_array = np.random.randint(1, 10, size=(3, 7))
np.unique(random_array)

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [ ]:
random_array[0]